// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqN8at1Y_MQ1OWGw4l0bZoj8rinrMurTk',
    appId: '1:31131385571:web:03ddfbcfd143249e450fd6',
    messagingSenderId: '31131385571',
    projectId: 'hiraya-dev',
    authDomain: 'hiraya-dev.firebaseapp.com',
    databaseURL: 'https://hiraya-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hiraya-dev.firebasestorage.app',
    measurementId: 'G-J0KVRNNJV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd2bKF9Diz_PZJL_3FbUTisWPQvECIXOo',
    appId: '1:31131385571:android:c4c93e56619ef4d1450fd6',
    messagingSenderId: '31131385571',
    projectId: 'hiraya-dev',
    databaseURL: 'https://hiraya-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hiraya-dev.firebasestorage.app',
  );
}
